name: Interface Acceptance Branch

on:
  push:
    branches:
      - test/interfaces-acceptance

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/terraform-test-reusable.yml
    with:
      packages: './internal/service/interfaces/...'
